name: Deploy Next Application
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t savinduc/next-app .

      - name: Push Docker Image
        run: docker push savinduc/next-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Latest Image
        run: docker pull savinduc/next-app:latest

      - name: Stop and Remove Existing Container (if running)
        run: docker rm -f nextjs-app-container || true

      - name: Run New Container
        run: docker run -d -p 3000:3000 --name nextjs-app-container savinduc/next-app:latest
